### ISSUE TITLE
getEngineBatchFilesPath() wrong on Mac and Linux

### ISSUE THREAD

**Issue by Lowingbn** [pampersrocker/buildbot-UnrealEngine#1]
On Mac and Linux the build scripts (e.g. Build.sh) are inside a subdirectory within Engine/Build/BatchFiles, so currently getEngineBatchFilesPath() is returning the wrong path for these platforms.

**Comment by pampersrocker** [comment]
Ah, thanks!

We currently do not target Linux or Mac, so I don't have a test platform or use case for those ;)

**Comment by pampersrocker** [comment]
I've cherry picked your commits from your repo ( https://github.com/Mercuna/buildbot-UnrealEngine ).
Some modifications were necessary, as the paths were actually correct for the UAT, but not for the UBT.... special cases, yay!

I've tried to unify the UnrealLogLineObserver to work on linux as well. We are going to start deploying a server on linux very soon, then I have an actual use case for Linux and can properly test this and create appropriate unit tests.

Release v0.2.2 contains those changes.

**Comment by Lowingbn** [comment]
I'm very pleased to see you've cherry picked the commits. The changes were made to quickly, so please do tidy them up as needed.

I'm not sure you can use MSLogLineObserver for the base class for the logger on Linux. I think there were end of lines problems with that, which is why I had two different logging classes.
